
[build]
  command = 'make'
  publish = 'public'

[[headers]]
  for = '/fonts/*'
  [headers.values]
    cache-control = 'public,max-age=31536000,immutable'

[[headers]]
  for = '/cache/*'
  [headers.values]
    cache-control = 'public,max-age=604800,immutable'

[[redirects]]
  from = '/*'
  to = '/index.html'
  status = 200
