
[build]
  command = 'make'
  publish = 'public'

[[headers]]
  for = '/fonts/*'
  [headers.value]
    cache-control = 'max-age=31536000,immutable'

[[redirects]]
  from = '/*'
  to = '/index.html'
  status = 200
