// Sidebar navigation for the demos section: route name, label, month, and year group.
// Pure navigation, nothing else; each demo's content lives in its own page component.
export const demoLinks = [
  { route: 'demo-python-todo', title: 'Python Todo', month: 'Jun', year: '2025' },
  { route: 'demo-reasonable', title: 'Reasonable', month: 'Oct', year: '2023' },
  { route: 'demo-amazon-price-check', title: 'Amazon Price Check', month: 'Aug', year: '2021' },
  // { route: 'demo-clickmart', title: 'Clickmart', month: 'Jul', year: '2021' },
  { route: 'demo-currency', title: 'Currency Exchange', month: 'May', year: '2021' },
  { route: 'demo-onclick-notes', title: 'Onclick Notes', month: 'Apr', year: '2021' },
  { route: 'demo-framework-challenge', title: 'Framework Challenge', month: 'Apr', year: '2021' },
  { route: 'demo-valorant-blog', title: 'Valorant Blog', month: 'Mar', year: '2021' },
  { route: 'demo-instatistics', title: 'Instatistics', month: 'Mar', year: '2021' },
  { route: 'demo-state-sync', title: 'State Sync', month: 'Feb', year: '2021' },
  { route: 'demo-resize', title: 'Resize', month: 'Feb', year: '2021' },
  { route: 'demo-discord-queue', title: 'Discord Message Queue', month: 'Dec', year: '2020' },
  { route: 'demo-almost-realtime', title: 'Almost Realtime', month: 'Feb', year: '2019' },
  { route: 'demo-dvd', title: 'DVD Video', month: 'Feb', year: '2019' },
  { route: 'demo-h8ball', title: 'h8ball', month: 'Feb', year: '2018' },
  { route: 'demo-vue-queue', title: 'Vue Queue Items', month: 'Nov', year: '2016' },
  { route: 'demo-roguelike', title: 'Roguelike', month: 'Oct', year: '2016' },
  { route: 'demo-css-3d-toggle', title: '3D Toggle Button', month: 'Sep', year: '2016' },
  { route: 'demo-vue-pagination', title: 'Vue Pagination', month: 'Sep', year: '2016' },
  { route: 'demo-emoji', title: 'Crying Emoji', month: 'Sep', year: '2016' },
  { route: 'demo-svg-clock', title: 'SVG Digital Clock', month: 'Jan', year: '2016' },
  { route: 'demo-ios-chat-bubbles', title: 'iOS Chat Bubbles', month: 'Mar', year: '2015' },
  { route: 'demo-jquery-dropdown', title: 'jQuery Dropdown Menu', month: 'Mar', year: '2015' },
  { route: 'demo-messenger', title: 'Messenger CSS', month: 'Dec', year: '2014' },
] as const
