import opentype from 'opentype.js'
import { z } from 'zod'
import { safeAsync } from '$common/safe.ts'
import { loadConfigSlice } from '../utils/config.utils.ts'

// Traces the site wordmark from the licensed display font into a Vue component, so the font file never ships.
// The font path comes from tools/config.json and points outside the repo, since the desktop license does not allow redistribution.
const configSchema = z.object({
  font: z.string(),
  text: z.string().default('Dustin Dowell'),
  output: z.string(),
})

const unitsPerEm = 1000

const config = await loadConfigSlice({ key: 'wordmark', schema: configSchema })

const trace = async (): Promise<string> => {
  const bytes = await Deno.readFile(config.font)
  const font = opentype.parse(bytes.buffer)
  const scale = unitsPerEm / font.unitsPerEm
  const path = font.getPath(config.text, 0, 0, unitsPerEm, { kerning: true })
  const advance = font.getAdvanceWidth(config.text, unitsPerEm, { kerning: true })
  const ascent = Math.round(font.ascender * scale)
  const descent = Math.round(Math.abs(font.descender) * scale)
  const width = Math.round(advance)
  const height = ascent + descent
  const data = path.toPathData(1)
  // The glyph box is taller than the em, so the image is sized to the em and pulled back into a one-em line box like the text was.
  const emHeight = (height / unitsPerEm).toFixed(3)
  const overhang = ((height - unitsPerEm) / unitsPerEm / 2).toFixed(3)
  return [
    "import { defineComponent } from 'vue'",
    '',
    `// Generated by tools/wordmark from ${config.text} set in the site display font. Do not edit by hand.`,
    `const viewBox = '0 -${ascent} ${width} ${height}'`,
    `const pathData = '${data}'`,
    '',
    'export default defineComponent({',
    "  name: 'Wordmark',",
    '  setup () {',
    '    return () => (',
    `      <svg aria-label='${config.text}' class='-my-[${overhang}em] block h-[${emHeight}em] w-auto fill-current' role='img' viewBox={viewBox}>`,
    '        <path d={pathData}/>',
    '      </svg>',
    '    )',
    '  },',
    '})',
    '',
  ].join('\n')
}

const { data, error } = await safeAsync(trace)
if (error || !data) {
  console.error(`Could not trace the wordmark from ${config.font}: ${error?.message ?? 'no output'}`)
  Deno.exit(1)
}
await Deno.writeTextFile(config.output, data)
console.log(`wrote ${config.output}`)
