name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Build project
        run: deno install --allow-scripts && make all

      - name: Move client to server
        run: cd server && deno task client:move

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: dustindowell
          entrypoint: ./index.ts
          root: ./server
